name: Tests
on:
  pull_request:
    branches:
      - 'dev'
    paths-ignore:
      - '**.md'
  push:
    branches:
      - 'dev'
    paths-ignore:
      - '**.md'
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Run style check
        run: ./gradlew ktlintCheck

      - name: Run tests
        run: ./gradlew testDebugUnitTest --stacktrace

  android_tests:
    runs-on: macos-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        api-level: [21, 28, 29]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86
          disable-animations: true
          script: ./gradlew app:connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=com.example.util.simpletimetracker.utils.Widget --stacktrace

      # For some reason widget tests make other tests to fail, so run them separately.
      - name: Run widget tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86
          disable-animations: true
          script: ./gradlew app:connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.annotation=com.example.util.simpletimetracker.utils.Widget --stacktrace

      - name: Upload tests results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: android_tests_results
          path: app/build/reports/androidTests/connected
